# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --select, I]
        exclude: '^(third_party)/.*'
      # Run the formatter.
      - id: ruff-format
        exclude: '^(third_party)/.*'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        exclude: '^(third_party|tests)/.*'
        args:
          - --strict
          - --ignore-missing-imports
          - --no-namespace-packages
          - --python-version=3.11
        entry: mypy
