name: skala-gpu
channels:
  - conda-forge
dependencies:
  - ase
  - azure-core
  - azure-identity
  - dftd3-python
  - e3nn
  - h5py
  - numpy
  - opt_einsum_fx
  - pyscf
  - python
  - pytorch-gpu
  - qcelemental
  - cuda-toolkit
  - cupy
  - cutensor
  - cuda-version ==12.*
  # Testing and development
  - pre-commit
  - pytest
  - pytest-cov
  - pip:
    - huggingface_hub
