[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "microsoft-skala"
version = "@VERSION@"
description = "Skala Exchange Correlation Functional"
authors = []
license-files = ["LICENSE.txt"]
readme = "README.md"
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 5 - Production/Stable",
]
requires-python = ">=3.10"
dependencies = [
    "skala==@VERSION@",
]
urls.repository = "https://github.com/microsoft/skala"
urls.documentation = "https://microsoft.github.io/skala"
urls.homepage = "https://aka.ms/dft"
