name: ftorch-dev
channels:
  - conda-forge
dependencies:
  # build requirements
  - fortran-compiler
  - c-compiler
  - cxx-compiler
  - cmake >=3.20,<4
  - ninja
  # host/runtime requirements
  - huggingface_hub
  - pytorch >=2.0 cpu_*

